### ISSUE TITLE
update to use latest node

### ISSUE THREAD

**Issue by fluttersiast** [kigary/update-pr-from-branch-name#1]

**Comment by kigary** [comment]
@yauhenuzum, thanks for the suggestion.
Please check this release: [v1.0.4](https://github.com/kigary/update-pr-from-branch-name/releases/tag/v1.0.4)

**Comment by fluttersiast** [comment]
Works like a charm, thanks!

**Comment by fluttersiast** [comment]
Ah, looks like had an exception now(

Error: Cannot find module '@actions/core'

Happened only with 1.0.4

Also looks like it's not possible to fetch version passing just v1

**Comment by kigary** [comment]
WIll check the issue and write here. Thanks!

**Comment by kigary** [comment]
I was able to check this only now. Should be fixed with this [PR](https://github.com/kigary/update-pr-from-branch-name/pull/3) merge. Also new version and tag has been released.

P.S.
passing just v1 won't work because there is no alias for it. Will find time to investigate how that works!
I am happy this action is helping you!
